export const browserCoreExamples = [
  "oni browser status",
  "oni browser start",
  "oni browser stop",
  "oni browser tabs",
  "oni browser open https://example.com",
  "oni browser focus abcd1234",
  "oni browser close abcd1234",
  "oni browser screenshot",
  "oni browser screenshot --full-page",
  "oni browser screenshot --ref 12",
  "oni browser snapshot",
  "oni browser snapshot --format aria --limit 200",
  "oni browser snapshot --efficient",
  "oni browser snapshot --labels",
];

export const browserActionExamples = [
  "oni browser navigate https://example.com",
  "oni browser resize 1280 720",
  "oni browser click 12 --double",
  'oni browser type 23 "hello" --submit',
  "oni browser press Enter",
  "oni browser hover 44",
  "oni browser drag 10 11",
  "oni browser select 9 OptionA OptionB",
  "oni browser upload /tmp/oni/uploads/file.pdf",
  'oni browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "oni browser dialog --accept",
  'oni browser wait --text "Done"',
  "oni browser evaluate --fn '(el) => el.textContent' --ref 7",
  "oni browser console --level error",
  "oni browser pdf",
];
